name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Gerar senha aleatória
        id: senha
        run: |
          export TF_ADMIN_PASSWORD=$(openssl rand -base64 16)
          echo "admin_password=\"$TF_ADMIN_PASSWORD\"" > terraform.auto.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Importar Resource Group existente
        run: terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-redhat-vm-001 || true

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
