name: Terraform Azure Deploy


on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Gerar senha aleatória
        id: senha
        run: |
          export TF_ADMIN_PASSWORD=$(openssl rand -base64 16)
          echo "admin_password=\"$TF_ADMIN_PASSWORD\"" > terraform.auto.tfvars
          echo "::set-output name=senha::$TF_ADMIN_PASSWORD"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Exibir comando SSH e senha
        run: |
          terraform output ssh_command
          echo "Senha gerada para azureuser: ${{ steps.senha.outputs.senha }}"
